version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
- package-ecosystem: cargo
  directory: /
  schedule:
    interval: weekly
  ignore:
  - dependency-name: anyhow
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: clap
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: serde
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: serde_with
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: thiserror
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: tokio
    update-types:
    - version-update:semver-minor
    - version-update:semver-patch
  - dependency-name: '*'
    update-types:
    - version-update:semver-patch
